### PR TITLE
Add detect_os for work on MacOS and Linux and more

### PR DESCRIPTION
**Pull request by bernardesarthur**
I had problems with macOS because the sed command is different between macOS and Linux. I created a function to detect the OS and adjust the _sed_ command for the two different systems.

I realized that this script generates _no ip prefix-list prefix_list_$asn_ from bgpq4, and I have fixed it.

Now, I see that the script is sometimes adding _set apply-groups TWITTER-BLOCK_ inside the Juniper option. I'm still working on this issue.

### CODE REVIEW

**Comment by bernardesarthur** [comment]
I fixed the multiple occurrences of apply groups in Juniper and I added removal commands in EOF.

**Comment by bernardesarthur** [comment]
I’ll work on this so we can use it to create policies for each specified platform. Thank's.

**Comment by bernardesarthur** [comment]
Testing, I'll be back soon.

**Comment by bernardesarthur** [comment]
I finished all changes today. Please merge if you can.

**Comment by andrediashexa** [comment]
Thank you mate. Merged.

**Pull request merged**
